<a href="https://colab.research.google.com/github/Shashank-sketchAl/Machine-Learning-Training/blob/main/MultiClassClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Details
Student Performance dataset using the Multi class classification

In [30]:
#from google.colab import files
#uploaded = files.upload()

In [31]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv('student_performance.csv')

In [33]:
df.head()

,Name,Age,Gender,Major,Living_Area,Parent_Education,Scholarship_Status,Part_Time_Job,Extracurricular_Activities,Internet_Access,...,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Exam_Proximity,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade
0,Linda Johnson,24,Female,Arts,Rural,Bachelor,No,No,No,Yes,...,6.69,77.3,3.6,No,52,43,69,66,58,C
1,Thomas Thomas,21,Male,Arts,Suburban,Master,No,No,No,Yes,...,7.34,59.7,7.3,Yes,59,64,74,68,66,C
2,Joseph Rodriguez,23,Male,STEM,Suburban,High School,Yes,No,No,Yes,...,6.78,56.0,2.9,No,81,72,67,69,72,B
3,Michael Wright,25,Male,STEM,Rural,High School,No,No,No,Yes,...,9.59,84.9,3.2,No,63,72,55,58,62,C
4,Jennifer Nguyen,25,Female,Arts,Urban,Bachelor,Yes,No,No,Yes,...,7.04,98.2,4.6,Yes,69,76,90,86,80,B

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Name                        1000 non-null   object
 1   Age                         1000 non-null   int64
 2   Gender                      1000 non-null   object
 3   Major                       1000 non-null   object
 4   Living_Area                 1000 non-null   object
 5   Parent_Education            1000 non-null   object
 6   Scholarship_Status          1000 non-null   object
 7   Part_Time_Job               1000 non-null   object
 8   Extracurricular_Activities  1000 non-null   object
 9   Internet_Access             1000 non-null   object
 10  Study_Hours_Per_Day         1000 non-null   float64
 11  Sleep_Hours_Per_Day         1000 non-null   float64
 12  Attendance_Rate             1000 non-null   float64
 13  Stress_Level                1000 non-null   float64
 14  Exam_Proximity              1000 non-null   object
 15  Math_Score                  1000 non-null   int64
 16  Science_Score               1000 non-null   int64
 17  Language_Score              1000 non-null   int64
 18  History_Score               1000 non-null   int64
 19  Average_Score               1000 non-null   int64
 20  Grade                       1000 non-null   object
dtypes: float64(4), int64(6), object(11)
memory usage: 164.2+ KB

In [35]:
df.isnull().sum()

Name                          0
Age                           0
Gender                        0
Major                         0
Living_Area                   0
Parent_Education              0
Scholarship_Status            0
Part_Time_Job                 0
Extracurricular_Activities    0
Internet_Access               0
Study_Hours_Per_Day           0
Sleep_Hours_Per_Day           0
Attendance_Rate               0
Stress_Level                  0
Exam_Proximity                0
Math_Score                    0
Science_Score                 0
Language_Score                0
History_Score                 0
Average_Score                 0
Grade                         0
dtype: int64

#Drop Unnecessary Column

In [36]:
df.drop('Name',axis=1,inplace=True)

In [37]:
df.head()

,Age,Gender,Major,Living_Area,Parent_Education,Scholarship_Status,Part_Time_Job,Extracurricular_Activities,Internet_Access,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Exam_Proximity,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade
0,24,Female,Arts,Rural,Bachelor,No,No,No,Yes,1.24,6.69,77.3,3.6,No,52,43,69,66,58,C
1,21,Male,Arts,Suburban,Master,No,No,No,Yes,3.67,7.34,59.7,7.3,Yes,59,64,74,68,66,C
2,23,Male,STEM,Suburban,High School,Yes,No,No,Yes,5.31,6.78,56.0,2.9,No,81,72,67,69,72,B
3,25,Male,STEM,Rural,High School,No,No,No,Yes,2.70,9.59,84.9,3.2,No,63,72,55,58,62,C
4,25,Female,Arts,Urban,Bachelor,Yes,No,No,Yes,3.59,7.04,98.2,4.6,Yes,69,76,90,86,80,B

#Separate Features and Target

Features = Input columns

Target = What we want to predict

In [38]:
X = df.drop('Grade', axis=1)

y = df['Grade']

In [39]:
X.head()

,Age,Gender,Major,Living_Area,Parent_Education,Scholarship_Status,Part_Time_Job,Extracurricular_Activities,Internet_Access,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Exam_Proximity,Math_Score,Science_Score,Language_Score,History_Score,Average_Score
0,24,Female,Arts,Rural,Bachelor,No,No,No,Yes,1.24,6.69,77.3,3.6,No,52,43,69,66,58
1,21,Male,Arts,Suburban,Master,No,No,No,Yes,3.67,7.34,59.7,7.3,Yes,59,64,74,68,66
2,23,Male,STEM,Suburban,High School,Yes,No,No,Yes,5.31,6.78,56.0,2.9,No,81,72,67,69,72
3,25,Male,STEM,Rural,High School,No,No,No,Yes,2.70,9.59,84.9,3.2,No,63,72,55,58,62
4,25,Female,Arts,Urban,Bachelor,Yes,No,No,Yes,3.59,7.04,98.2,4.6,Yes,69,76,90,86,80

In [40]:
y.head()

0    C
1    C
2    B
3    C
4    B
Name: Grade, dtype: object

#Encode Target Variable

Machine Learning models cannot understand text labels.

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [42]:
le = LabelEncoder()

y = le.fit_transform(y)

#Find Categorical Columns

Non-numeric columns need encoding.

In [43]:
X.select_dtypes(include='object').columns

Index(['Gender', 'Major', 'Living_Area', 'Parent_Education',
       'Scholarship_Status', 'Part_Time_Job', 'Extracurricular_Activities',
       'Internet_Access', 'Exam_Proximity'],
      dtype='object')

#Perform One-Hot Encoding

Convert text categories into numbers.

In [44]:
X = pd.get_dummies(X, drop_first=True)

In [45]:
X.head()

,Age,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,...,Living_Area_Suburban,Living_Area_Urban,Parent_Education_High School,Parent_Education_Master,Parent_Education_PhD,Scholarship_Status_Yes,Part_Time_Job_Yes,Extracurricular_Activities_Yes,Internet_Access_Yes,Exam_Proximity_Yes
0,24,1.24,6.69,77.3,3.6,52,43,69,66,58,...,False,False,False,False,False,False,False,False,True,False
1,21,3.67,7.34,59.7,7.3,59,64,74,68,66,...,True,False,False,True,False,False,False,False,True,True
2,23,5.31,6.78,56.0,2.9,81,72,67,69,72,...,True,False,True,False,False,True,False,False,True,False
3,25,2.70,9.59,84.9,3.2,63,72,55,58,62,...,False,False,True,False,False,False,False,False,True,False
4,25,3.59,7.04,98.2,4.6,69,76,90,86,80,...,False,True,False,False,False,True,False,False,True,True

#Train-Test Split

Train model on 80% data and test on 20%.

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [47]:
print(X_train.shape)

(800, 24)

In [48]:
print(X_test.shape)

(200, 24)

#Feature Scaling

Bring all features to a similar range.

In [49]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [50]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report

In [51]:
model = RandomForestClassifier(n_estimators=100,random_state=42)

In [52]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

#Predictions

In [53]:
y_pred = model.predict(X_test)

#Accuracy

In [54]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.995

#Detailed Evaluation

In [55]:
#print(classification_report(y_test, y_pred))